### PR TITLE
Add support for Python 3.12.

### PR DESCRIPTION
**Pull request by perrinjerome**

### CODE REVIEW

**Comment by perrinjerome** [comment]
@icemac I ran `bin/python config-package.py ../../Products.PythonScripts/ --type zope-product` 

py312 fails on CI, because of https://github.com/buildout/buildout/issues/648 . My understanding is that this error is potentially everywhere in buildout based packages, I don't understand why only 3.12 is affected, but this looks like an old compatible version of setuptools was already installed for other python versions but not for python3.12

in the logs of [py311](https://github.com/zopefoundation/Products.PythonScripts/actions/runs/9219350453/job/25364350453) we can see 

```
py311: freeze> python -m pip freeze --all
py311: pip==24.0,setuptools==69.5.1,wheel==0.43.0,zc.buildout==3.0.1

```

this is using a compatible old setuptools and test passed for 3.11.


but in the logs of [py312](https://github.com/zopefoundation/Products.PythonScripts/actions/runs/9219383896/job/25364445111?pr=63)

```
py312: freeze> python -m pip freeze --all
py312: pip==23.1.2,setuptools==70.0.0,wheel==0.43.0,zc.buildout==3.0.1
```

using incompatible new setuptools and there's this error.

I don't really need this pull request now, I just noticed that there was no python3.12 so I tried to enable it.

All this makes me wonder if it makes sense to pin `setuptools < 70` in all zopefoundation repositories for now ?

**Comment by icemac** [comment]
Hi @perrinjerome `zope-product` was not yet pinned to `setuptools < 69`. I just added it. For details see https://github.com/zopefoundation/meta/pull/243 and https://github.com/buildout/buildout/issues/648

**Comment by icemac** [comment]
So you could pull in the changes in `meta` and run config again. This time please run it with the `--branch` option pointing to this branch otherwise it will create a new one.

**Comment by perrinjerome** [comment]
Thank you @icemac I did not notice that this was already (partially) supported. It should be OK now

**Review by dataflake — APPROVED** [review]

**Comment by perrinjerome** [comment]
Thank you

**Pull request merged**
