### PR TITLE
Add zodbupdate entry point for PythonScript objects

### PR DESCRIPTION
**Pull request by rbu**
Ref https://github.com/zopefoundation/Zope/pull/285

### CODE REVIEW

**Comment by rbu** [comment]
@icemac Got an idea why the test fails? IMO RestrictedPython's buildout.cfg should install Zope master and that requires RestrictedPython == 4.0b5

**Comment by icemac** [comment]
@rbu `buildout.cfg` uses 
https://zopefoundation.github.io/Zope/releases/master/versions-prod.cfg as versions which still contains `RestrictedPython 4.0b4` which is too old for `Products.PythonScripts`. The easiest way would be to checkout `RestrictedPython` in `buildout.cfg`, too.

**Comment by rbu** [comment]
@icemac Thanks for the pointer. So "master" in the gh-pages is not really "master", but "latest". I'd vote for a rename.

**Review by icemac — APPROVED** [review]
LGTM.

**Comment by icemac** [comment]
> So "master" in the gh-pages is not really "master", but "latest". I'd vote for a rename.

I created zopefoundation/Zope#333 to track your vote.

**Pull request merged**
