### PR TITLE
Add dumping/reading Proxy Roles to/from proxy_roles header

### PR DESCRIPTION
**Pull request by grasslasts**
Add dumping/reading Proxy Roles to/from proxy_roles header. Roles represented as comma-separated list.

Example:

```
## Script (Python) "test1"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=
##proxy_roles=Role1,Role2
##title=
##
return "OK"
```

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
The first thing I wonder here is: could this be abused? Let's say you allow simple members or authenticated users to upload python scripts. (Don't do this please...) With the above, they could add Manager as proxy role and execute all kinds of code that they are not supposed to.

So the current roles of the user should be checked. Probably only global roles, not local roles, as the script could do something in the global site instead of just in a local folder. Only the global roles of the user should be allowed as `proxy_roles`.

Note: I don't remember the last time I used proxy roles for an own script. So I may be misremembering what you can do with them.

**Comment by tseaver** [comment]
@lein Thank you for the patch!  Unfortunately, I'm going to have to vote -1 to this feature, because it breaks the fundamental TTW security model:

-  Editing a TTW script requires a different permission than changing its proxy roles:  The latter role is typically only granted to admin/manager users, and already has a dedicated UI.
- Filesystem-based scripts (e.g., in the CMF) have a different way to spell proxy roles.

**Comment by tseaver** [comment]
Read [here](https://docs.zope.org/zope2/zope2book/Security.html#proxy-roles) how proxy roles can be used to bypass normal restrictions.

**Comment by ivan-antonyuck** [comment]
What if before setting proxy roles we add a check if a user can do this?

**Pull request closed without merging**
