### PR TITLE
Mark params as public to make header (parameters) accessible but not definition

### PR DESCRIPTION
**Pull request by katomaso**
Scripts are targets of URL calls thus even unauthorised user should be able to see necessary arguments to call such a function. The only hidden thing is the implementation (following .h/.c separation).

### CODE REVIEW

**Comment by icemac** [comment]
@katomaso Thank you for your PR. I am not sure about the security implications of this change, so I'd like to have some more information about your actual use case where you need this change.

**Comment by icemac** [comment]
@katomaso Ping. I'd like to know what you want to achieve by this change.

**Comment by katomaso** [comment]
Hello,
the rationale behind this change is being able to call a script without the publisher. For that one needs to know the names of its parameters.

**Comment by tseaver** [comment]
@katomaso 

> the rationale behind this change is being able to call a script without the publisher. For that one needs to know the names of its parameters.

I'm not sure I understand:  declaring `params` public only affects how they can be accessed from untrusted code, i.e. from within the script itself, or another script / DTML method / page template.  How is untrusted code in play if you aren't running under the publisher?

**Comment by katomaso** [comment]
In our application - we need to generate a HATEOAS response on a REST request. This response includes possible actions on a document. Such actions can be either a `Product.PythonScript` or Product's class method.

Now I have a set of keys from a `HttpRequest` object. Since I do not know if all possible actions accept `**kwargs` I need to assign correct parameters from HttpRequest to the action call. Thus I need to be able to read their parameters. And the script generating the HATEOAS response might run with no special permissions - those are checked when running the actions (Product.PythonScript etc.).

Does that respond your question?

**Comment by tseaver** [comment]
@katomaso 

> the script generating the HATEOAS response 

Is that a PythonScript?

**Comment by tseaver** [comment]
I've gotta say that writing framework-y code in a PythonScript (dispatching request data onto callables with unknown signatures) seems like misery to me -- can't be tested, can't be checked in to VCS, etc.

**Comment by katomaso** [comment]
I agree. I am actually off the project for at least half a year so I don't care much about result now.

I just thought you will say "Oh true function declarations are always public! It's a mistake on our side. I'll merge."

**Comment by tseaver** [comment]
Thanks for your effort!  I'm going to close without merging, as I can't see that the usecase is widespread, and `params` seems like it should be covered by the same permissions as e.g., `document_src`.

**Pull request closed without merging**
