### PR TITLE
Add support for Python 3.13

### PR DESCRIPTION
**Pull request by perrinjerome**

### CODE REVIEW

**Comment by perrinjerome** [comment]
I ran latest version of meta's config-package and updated setup.py

**Review by dataflake — APPROVED** [review]
To fix the expected tests you need to run that last step that adjusts the branch protection rules as well. Or you fix it by hand.

**Comment by perrinjerome** [comment]
Thank you @dataflake I tried but I think I can not do it because I don't have permissions. I also don't see the "Settings" button on github to do it by hand

image

**Comment by dataflake** [comment]
OK, I see what you mean. It's not your fault, but it kills the benefit of others doing this work when I have to step in and fix that stuff manually, anway.

**Comment by perrinjerome** [comment]
Thank you !

**Pull request merged**
