### PR TITLE
Fix MANIFEST.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM

**Comment by icemac** [comment]
Coverage had dropped, so I removed some unused code from the tests, see https://github.com/zopefoundation/Products.PythonScripts/pull/57/commits/37ccf4ffdc1fcc3e1d4f567fe8de1ed499d1b880

**Comment by icemac** [comment]
@mauritsvanrees Please re-review.

**Review by mauritsvanrees — APPROVED** [review]
I don't see these test classes being used outside of this package, so this is fine with me.

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
